#!/bin/bash
# echo $(echo  & mpstat | awk 'FNR == 4 {print $4}') 

separator_front() {
    echo -n "{
        \"full_text\":\"\",
        \"separator\":false,
        \"separator_block_width\":0,
        \"border\":\"#000000\",
        \"border_left\":0,
        \"border_right\":0,
        \"border_top\":2,
        \"border_bottom\":2,
        \"color\":\"$1\",        
        \"background\":\"#000000\"
    },"
}
common() {
  echo -n "\"border\": \"#5e5e5e\","
  echo -n "\"separator\":false,"
  echo -n "\"separator_block_width\":0,"
  echo -n "\"border_top\":2,"
  echo -n "\"border_bottom\":2,"
  echo -n "\"border_left\":0,"
  echo -n "\"border_right\":0"
}

cpu_load() {
    CPU_LOAD=$(mpstat | awk ' FNR == 4 { print $4 }')
        # separator_front "#303030"
        echo -n "{"
        echo -n "\"name\":\"cpu_load\","
        echo -n "\"full_text\":\" 龍 ${CPU_LOAD} \","
        echo -n "\"color\":\"#ffffff\","
        echo -n "\"background\":\"#000000\","
        common
        echo -n "},"
}
cpu_load