#!/bin/bash

separator_front() {
    echo -n "{
        \"full_text\":\"\",
        \"separator\":false,
        \"separator_block_width\":0,
        \"border\":\"#000000\",
        \"border_left\":0,
        \"border_right\":0,
        \"border_top\":2,
        \"border_bottom\":2,
        \"color\":\"$1\",        
        \"background\":\"#000000\"
    },"
}

common() {
  echo -n "\"border\": \"#5e5e5e\","
  echo -n "\"separator\":false,"
  echo -n "\"separator_block_width\":0,"
  echo -n "\"border_top\":2,"
  echo -n "\"border_bottom\":2,"
  echo -n "\"border_left\":0,"
  echo -n "\"border_right\":0"
}


disk_usage () {
    
    DISK=$(df -h | grep /dev/sda4 | awk '{print $4}')
        # separator_front "#303030"
        echo -n "{"
        echo -n "\"name\":\"disk\","
        echo -n "\"full_text\":\"  ${DISK} \","
        echo -n "\"color\":\"#ffffff\","
        echo -n "\"background\":\"#000000\","
        common
        echo -n "},"
}
disk_usage