#!/bin/bash
separator_front() {
    echo -n "{
        \"full_text\":\"\",
        \"separator\":false,
        \"separator_block_width\":0,
        \"border\":\"#000000\",
        \"border_left\":0,
        \"border_right\":0,
        \"border_top\":2,
        \"border_bottom\":2,
        \"color\":\"$1\",        
        \"background\":\"#000000\"
    },"
}